INSERT INTO 
`category` (`created_at`, `name`, `updated_at`, `type`, `color`) VALUES
 (now(), 'Ciências', now(), 'quiz', "#3B82F6" ),
 (now(), 'Matemática', now(), 'quiz', "#10B981" ),
 (now(), 'Linguagens', now(), 'quiz', "#EF4444"),
 (now(), 'Humanas', now(), 'quiz', "#8B5CF6");

INSERT INTO question (statement, exam, category_id, created_at, updated_at, deleted_at) VALUES
('A fotossíntese é um processo realizado principalmente por:', 'ENEM', '1', NOW(), NOW(), NULL),
('O átomo é composto basicamente por:', 'ENEM', '1', NOW(), NOW(), NULL),
('A unidade básica da vida é:', 'ENEM', '1', NOW(), NOW(), NULL),
('O efeito estufa é causado principalmente pelo aumento de:', 'ENEM', '1', NOW(), NOW(), NULL),
('A água ferve a 100°C em condições normais de:', 'ENEM', '1', NOW(), NOW(), NULL),
('As ligações iônicas ocorrem entre:', 'ENEM', '1', NOW(), NOW(), NULL),
('A primeira lei de Newton trata da:', 'ENEM', '1', NOW(), NOW(), NULL),
('O DNA é responsável por:', 'ENEM', '1', NOW(), NOW(), NULL),
('A fotossíntese ocorre em organelas chamadas:', 'ENEM', '1', NOW(), NOW(), NULL),
('A camada de ozônio protege a Terra de:', 'ENEM', '1', NOW(), NOW(), NULL),
('O princípio de Arquimedes está relacionado à:', 'ENEM', '1', NOW(), NOW(), NULL),
('A velocidade média é calculada por:', 'ENEM', '1', NOW(), NOW(), NULL),
('O pH de uma solução neutra é:', 'ENEM', '1', NOW(), NOW(), NULL),
('As plantas absorvem água e sais minerais por meio das:', 'ENEM', '1', NOW(), NOW(), NULL),
('O gás responsável pela respiração celular é:', 'ENEM', '1', NOW(), NOW(), NULL),
('As leis da termodinâmica estudam:', 'ENEM', '1', NOW(), NOW(), NULL),
('A energia potencial gravitacional depende de:', 'ENEM', '1', NOW(), NOW(), NULL),
('O elemento mais abundante no corpo humano é:', 'ENEM', '1', NOW(), NOW(), NULL),
('A corrente elétrica é o movimento ordenado de:', 'ENEM', '1', NOW(), NOW(), NULL),
('A principal função das mitocôndrias é:', 'ENEM', '1', NOW(), NOW(), NULL),
('A decomposição da luz branca em várias cores é chamada de:', 'ENEM', '1', NOW(), NOW(), NULL),
('O símbolo químico do ferro é:', 'ENEM', '1', NOW(), NOW(), NULL),
('O som não se propaga no:', 'ENEM', '1', NOW(), NOW(), NULL),
('O tipo sanguíneo universal para doação é:', 'ENEM', '1', NOW(), NOW(), NULL),
('A velocidade da luz no vácuo é aproximadamente:', 'ENEM', '1', NOW(), NOW(), NULL),
('O resultado de 8 × 7 é:', 'ENEM', '1', NOW(), NOW(), NULL),
('O número 0,25 é equivalente a:', 'ENEM', '2', NOW(), NOW(), NULL),
('A raiz quadrada de 81 é:', 'ENEM', '2', NOW(), NOW(), NULL),
('A área de um quadrado de lado 6 cm é:', 'ENEM', '2', NOW(), NOW(), NULL),
('O perímetro de um triângulo com lados 3 cm, 4 cm e 5 cm é:', 'ENEM', '2', NOW(), NOW(), NULL),
('O valor de 2³ é:', 'ENEM', '2', NOW(), NOW(), NULL),
('A soma dos ângulos internos de um triângulo é:', 'ENEM', '2', NOW(), NOW(), NULL),
('O logaritmo de 100 na base 10 é:', 'ENEM', '2', NOW(), NOW(), NULL),
('Em uma progressão aritmética (PA) com razão 2, o termo seguinte de 5 é:', 'ENEM', '2', NOW(), NOW(), NULL),
('O volume de um cubo de aresta 4 cm é:', 'ENEM', '2', NOW(), NOW(), NULL),
('O valor de π é aproximadamente:', 'ENEM', '2', NOW(), NOW(), NULL),
('Se x = 2, então 3x + 4 = ?', 'ENEM', '2', NOW(), NOW(), NULL),
('A média aritmética de 6, 8 e 10 é:', 'ENEM', '2', NOW(), NOW(), NULL),
('Um triângulo equilátero tem:', 'ENEM', '2', NOW(), NOW(), NULL),
('Em um círculo, o diâmetro é:', 'ENEM', '2', NOW(), NOW(), NULL),
('A porcentagem equivalente a 0,75 é:', 'ENEM', '2', NOW(), NOW(), NULL),
('O número primo entre 10 e 20 é:', 'ENEM', '2', NOW(), NOW(), NULL),
('A fórmula da área do triângulo é:', 'ENEM', '2', NOW(), NOW(), NULL),
('O inverso multiplicativo de 5 é:', 'ENEM', '2', NOW(), NOW(), NULL),
('Em um gráfico, o eixo X representa normalmente:', 'ENEM', '2', NOW(), NOW(), NULL),
('O perímetro de um quadrado de lado 5 é:', 'ENEM', '2', NOW(), NOW(), NULL),
('A fração equivalente a 0,5 é:', 'ENEM', '2', NOW(), NOW(), NULL),
('O resultado de (-3)² é:', 'ENEM', '2', NOW(), NOW(), NULL),
('Em um retângulo de base 8 e altura 3, a área é:', 'ENEM', '2', NOW(), NOW(), NULL),
('O conjunto dos números inteiros inclui:', 'ENEM', '2', NOW(), NOW(), NULL),
('O gênero textual "crônica" caracteriza-se principalmente por:', 'ENEM', '3', NOW(), NOW(), NULL),
('Na língua portuguesa, o sujeito é o termo da oração que:', 'ENEM', '3', NOW(), NOW(), NULL),
('O advérbio é a classe gramatical que:', 'ENEM', '3', NOW(), NOW(), NULL),
('A linguagem conotativa é usada quando:', 'ENEM', '3', NOW(), NOW(), NULL),
('O Modernismo brasileiro iniciou-se com:', 'ENEM', '3', NOW(), NOW(), NULL),
('O plural de "cidadão" é:', 'ENEM', '3', NOW(), NOW(), NULL),
('O verbo "estudar" no futuro do presente, 1ª pessoa do singular, é:', 'ENEM', '3', NOW(), NOW(), NULL),
('O pronome "me" em "Ele me viu" exerce função de:', 'ENEM', '3', NOW(), NOW(), NULL),
('O texto publicitário tem como principal objetivo:', 'ENEM', '3', NOW(), NOW(), NULL),
('O uso de rimas e ritmo é característico de:', 'ENEM', '3', NOW(), NOW(), NULL),
('O autor de "Os Lusíadas" é:', 'ENEM', '3', NOW(), NOW(), NULL),
('O romance "Dom Casmurro" foi escrito por:', 'ENEM', '3', NOW(), NOW(), NULL),
('O termo "verde esperança" apresenta:', 'ENEM', '3', NOW(), NOW(), NULL),
('Em "Pedro correu rapidamente", o termo "rapidamente" é:', 'ENEM', '3', NOW(), NOW(), NULL),
('O discurso direto é caracterizado por:', 'ENEM', '3', NOW(), NOW(), NULL),
('A variação linguística reflete:', 'ENEM', '3', NOW(), NOW(), NULL),
('A intertextualidade ocorre quando:', 'ENEM', '3', NOW(), NOW(), NULL),
('O gênero notícia tem como característica:', 'ENEM', '3', NOW(), NOW(), NULL),
('Em "A casa é velha", o termo "velha" é:', 'ENEM', '3', NOW(), NOW(), NULL),
('O verbo "ir" no pretérito perfeito, 3ª pessoa do plural, é:', 'ENEM', '3', NOW(), NOW(), NULL),
('Fernando Pessoa é conhecido por:', 'ENEM', '3', NOW(), NOW(), NULL),
('A função emotiva da linguagem está centrada:', 'ENEM', '3', NOW(), NOW(), NULL),
('Em "Compre já!", temos um exemplo de:', 'ENEM', '3', NOW(), NOW(), NULL),
('O plural de "mão" é:', 'ENEM', '3', NOW(), NOW(), NULL),
('O verbo "ser" no presente do indicativo, 1ª pessoa do singular, é:', 'ENEM', '3', NOW(), NOW(), NULL),
('A Revolução Francesa foi marcada por ideais de:', 'ENEM', '4', NOW(), NOW(), NULL),
('O Iluminismo se opôs principalmente ao:', 'ENEM', '4', NOW(), NOW(), NULL),
('O feudalismo era caracterizado por:', 'ENEM', '4', NOW(), NOW(), NULL),
('A escravidão africana no Brasil teve papel importante na:', 'ENEM', '4', NOW(), NOW(), NULL),
('A Guerra Fria foi marcada por:', 'ENEM', '4', NOW(), NOW(), NULL),
('O Mercantilismo defendia:', 'ENEM', '4', NOW(), NOW(), NULL),
('A urbanização no Brasil gerou:', 'ENEM', '4', NOW(), NOW(), NULL),
('A ONU foi criada com o objetivo de:', 'ENEM', '4', NOW(), NOW(), NULL),
('A Revolução Industrial teve início na:', 'ENEM', '4', NOW(), NOW(), NULL),
('O apartheid foi um regime de:', 'ENEM', '4', NOW(), NOW(), NULL),
('A Constituição de 1988 é chamada de Constituição Cidadã" porque:', 'ENEM', '4', NOW(), NOW(), NULL),
('O Tratado de Tordesilhas dividiu o mundo entre:', 'ENEM', '4', NOW(), NOW(), NULL),
('Karl Marx criticou o capitalismo por:', 'ENEM', '4', NOW(), NOW(), NULL),
('A Revolta dos Malês (1835) foi liderada por:', 'ENEM', '4', NOW(), NOW(), NULL),
('O Renascimento Cultural valorizou:', 'ENEM', '4', NOW(), NOW(), NULL),
('A Guerra do Paraguai envolveu:', 'ENEM', '4', NOW(), NOW(), NULL),
('A cidadania está relacionada a:', 'ENEM', '4', NOW(), NOW(), NULL),
('O neoliberalismo defende:', 'ENEM', '4', NOW(), NOW(), NULL),
('O movimento Diretas Já pedia:', 'ENEM', '4', NOW(), NOW(), NULL),
('O conceito de "meio ambiente" envolve:', 'ENEM', '4', NOW(), NOW(), NULL),
('O conceito de mais-valia explica:', 'ENEM', '4', NOW(), NOW(), NULL),
('A Primeira Guerra Mundial foi causada, entre outros fatores, por:', 'ENEM', '4', NOW(), NOW(), NULL),
('O movimento iluminista valorizava:', 'ENEM', '4', NOW(), NOW(), NULL),
('O sistema capitalista tem como base:', 'ENEM', '4', NOW(), NOW(), NULL),
('A independência do Brasil foi proclamada por:', 'ENEM', '4', NOW(), NOW(), NULL);

INSERT INTO answer (question_id, statement, is_correct, created_at, updated_at, deleted_at) VALUES 
(1, 'Animais', FALSE, NOW(), NOW(), NULL),
(1, 'Fungos', FALSE, NOW(), NOW(), NULL),
(1, 'Plantas ⭐', TRUE, NOW(), NOW(), NULL),
(1, 'Vírus', FALSE, NOW(), NOW(), NULL),
(1, 'Bactérias', FALSE, NOW(), NOW(), NULL),
(2, 'Elétrons, prótons e nêutrons ⭐', TRUE, NOW(), NOW(), NULL),
(2, 'Moléculas e células', FALSE, NOW(), NOW(), NULL),
(2, 'Íons e gases', FALSE, NOW(), NOW(), NULL),
(2, 'Núcleos e membranas', FALSE, NOW(), NOW(), NULL),
(2, 'Polímeros', FALSE, NOW(), NOW(), NULL),
(3, 'O tecido', FALSE, NOW(), NOW(), NULL),
(3, 'O órgão', FALSE, NOW(), NOW(), NULL),
(3, 'A célula ⭐', TRUE, NOW(), NOW(), NULL),
(3, 'O átomo', FALSE, NOW(), NOW(), NULL),
(3, 'A molécula', FALSE, NOW(), NOW(), NULL),
(4, 'Oxigênio', FALSE, NOW(), NOW(), NULL),
(4, 'Gases poluentes ⭐', TRUE, NOW(), NOW(), NULL),
(4, 'Nitrogênio', FALSE, NOW(), NOW(), NULL),
(4, 'Ozonio', FALSE, NOW(), NOW(), NULL),
(4, 'Vapor d’água', FALSE, NOW(), NOW(), NULL),
(5, 'Temperatura e pressão ⭐', TRUE, NOW(), NOW(), NULL),
(5, 'Pressão e volume', FALSE, NOW(), NOW(), NULL),
(5, 'Densidade e calor', FALSE, NOW(), NOW(), NULL),
(5, 'Condutividade e tensão', FALSE, NOW(), NOW(), NULL),
(5, 'Altitude e latitude', FALSE, NOW(), NOW(), NULL),
(6, 'Átomos que compartilham elétrons', FALSE, NOW(), NOW(), NULL),
(6, 'Íons de cargas opostas ⭐', TRUE, NOW(), NOW(), NULL),
(6, 'Moléculas polares', FALSE, NOW(), NOW(), NULL),
(6, 'Gases nobres', FALSE, NOW(), NOW(), NULL),
(6, 'Átomos idênticos', FALSE, NOW(), NOW(), NULL),
(7, 'Força resultante', FALSE, NOW(), NOW(), NULL),
(7, 'Inércia ⭐', TRUE, NOW(), NOW(), NULL),
(7, 'Gravidade', FALSE, NOW(), NOW(), NULL),
(7, 'Ação e reação', FALSE, NOW(), NOW(), NULL),
(7, 'Energia', FALSE, NOW(), NOW(), NULL),
(8, 'Produzir energia', FALSE, NOW(), NOW(), NULL),
(8, 'Armazenar informações genéticas ⭐', TRUE, NOW(), NOW(), NULL),
(8, 'Reproduzir proteínas', FALSE, NOW(), NOW(), NULL),
(8, 'Controlar o metabolismo', FALSE, NOW(), NOW(), NULL),
(8, 'Formar lipídios', FALSE, NOW(), NOW(), NULL),
(9, 'Mitocôndrias', FALSE, NOW(), NOW(), NULL),
(9, 'Lisossomos', FALSE, NOW(), NOW(), NULL),
(9, 'Cloroplastos ⭐', TRUE, NOW(), NOW(), NULL),
(9, 'Ribossomos', FALSE, NOW(), NOW(), NULL),
(9, 'Centríolos', FALSE, NOW(), NOW(), NULL),
(10, 'Raios infravermelhos', FALSE, NOW(), NOW(), NULL),
(10, 'Raios ultravioleta ⭐', TRUE, NOW(), NOW(), NULL),
(10, 'Luz visível', FALSE, NOW(), NOW(), NULL),
(10, 'Calor solar', FALSE, NOW(), NOW(), NULL),
(10, 'Radiação infrassônica', FALSE, NOW(), NOW(), NULL),
(11, 'Gravidade', FALSE, NOW(), NOW(), NULL),
(11, 'Flutuação dos corpos ⭐', TRUE, NOW(), NOW(), NULL),
(11, 'Atrito', FALSE, NOW(), NOW(), NULL),
(11, 'Pressão atmosférica', FALSE, NOW(), NOW(), NULL),
(11, 'Força centrífuga', FALSE, NOW(), NOW(), NULL),
(12, 'Espaço/tempo ⭐', TRUE, NOW(), NOW(), NULL),
(12, 'Tempo × espaço', FALSE, NOW(), NOW(), NULL),
(12, 'Massa/força', FALSE, NOW(), NOW(), NULL),
(12, 'Energia/potência', FALSE, NOW(), NOW(), NULL),
(12, 'Peso × aceleração', FALSE, NOW(), NOW(), NULL),
(13, '1', FALSE, NOW(), NOW(), NULL),
(13, '5', FALSE, NOW(), NOW(), NULL),
(13, '7 ⭐', TRUE, NOW(), NOW(), NULL),
(13, '9', FALSE, NOW(), NOW(), NULL),
(13, '14', FALSE, NOW(), NOW(), NULL),
(14, 'Folhas', FALSE, NOW(), NOW(), NULL),
(14, 'Raízes ⭐', TRUE, NOW(), NOW(), NULL),
(14, 'Flores', FALSE, NOW(), NOW(), NULL),
(14, 'Frutas', FALSE, NOW(), NOW(), NULL),
(14, 'Sementes', FALSE, NOW(), NOW(), NULL),
(15, 'Gás carbônico', FALSE, NOW(), NOW(), NULL),
(15, 'Oxigênio ⭐', TRUE, NOW(), NOW(), NULL),
(15, 'Nitrogênio', FALSE, NOW(), NOW(), NULL),
(15, 'Hidrogênio', FALSE, NOW(), NOW(), NULL),
(15, 'Hélio', FALSE, NOW(), NOW(), NULL),
(16, 'Movimento', FALSE, NOW(), NOW(), NULL),
(16, 'Energia e calor ⭐', TRUE, NOW(), NOW(), NULL),
(16, 'Luz', FALSE, NOW(), NOW(), NULL),
(16, 'Eletricidade', FALSE, NOW(), NOW(), NULL),
(16, 'Som', FALSE, NOW(), NOW(), NULL),
(17, 'Massa, gravidade e altura ⭐', TRUE, NOW(), NOW(), NULL),
(17, 'Massa e volume', FALSE, NOW(), NOW(), NULL),
(17, 'Tempo e aceleração', FALSE, NOW(), NOW(), NULL),
(17, 'Calor e pressão', FALSE, NOW(), NOW(), NULL),
(17, 'Densidade', FALSE, NOW(), NOW(), NULL),
(18, 'Carbono', FALSE, NOW(), NOW(), NULL),
(18, 'Hidrogênio', FALSE, NOW(), NOW(), NULL),
(18, 'Oxigênio ⭐', TRUE, NOW(), NOW(), NULL),
(18, 'Nitrogênio', FALSE, NOW(), NOW(), NULL),
(18, 'Cálcio', FALSE, NOW(), NOW(), NULL),
(19, 'Prótons', FALSE, NOW(), NOW(), NULL),
(19, 'Nêutrons', FALSE, NOW(), NOW(), NULL),
(19, 'Elétrons ⭐', TRUE, NOW(), NOW(), NULL),
(19, 'Íons positivos', FALSE, NOW(), NOW(), NULL),
(19, 'Moléculas', FALSE, NOW(), NOW(), NULL),
(20, 'Armazenar DNA', FALSE, NOW(), NOW(), NULL),
(20, 'Produzir energia (ATP) ⭐', TRUE, NOW(), NOW(), NULL),
(20, 'Regular o pH', FALSE, NOW(), NOW(), NULL),
(20, 'Sintetizar proteínas', FALSE, NOW(), NOW(), NULL),
(20, 'Degradar lipídios', FALSE, NOW(), NOW(), NULL),
(21, 'Absorção', FALSE, NOW(), NOW(), NULL),
(21, 'Dispersão ⭐', TRUE, NOW(), NOW(), NULL),
(21, 'Refração', FALSE, NOW(), NOW(), NULL),
(21, 'Reflexão', FALSE, NOW(), NOW(), NULL),
(21, 'Difração', FALSE, NOW(), NOW(), NULL),
(22, 'Fe ⭐', TRUE, NOW(), NOW(), NULL),
(22, 'Fi', FALSE, NOW(), NOW(), NULL),
(22, 'F', FALSE, NOW(), NOW(), NULL),
(22, 'Fo', FALSE, NOW(), NOW(), NULL),
(22, 'Fr', FALSE, NOW(), NOW(), NULL),
(23, 'Ar', FALSE, NOW(), NOW(), NULL),
(23, 'Água', FALSE, NOW(), NOW(), NULL),
(23, 'Vácuo ⭐', TRUE, NOW(), NOW(), NULL),
(23, 'Sólido', FALSE, NOW(), NOW(), NULL),
(23, 'Líquido', FALSE, NOW(), NOW(), NULL),
(24, 'A', FALSE, NOW(), NOW(), NULL),
(24, 'B', FALSE, NOW(), NOW(), NULL),
(24, 'AB', FALSE, NOW(), NOW(), NULL),
(24, 'O negativo ⭐', TRUE, NOW(), NOW(), NULL),
(24, 'O positivo', FALSE, NOW(), NOW(), NULL),
(25, '300 km/s', FALSE, NOW(), NOW(), NULL),
(25, '3.000 km/s', FALSE, NOW(), NOW(), NULL),
(25, '300.000 km/s ⭐', TRUE, NOW(), NOW(), NULL),
(25, '3.000.000 km/s', FALSE, NOW(), NOW(), NULL),
(25, '30.000 km/s', FALSE, NOW(), NOW(), NULL),
(26, '54', FALSE, NOW(), NOW(), NULL),
(26, '56 ⭐', TRUE, NOW(), NOW(), NULL),
(26, '49', FALSE, NOW(), NOW(), NULL),
(26, '57', FALSE, NOW(), NOW(), NULL),
(26, '64', FALSE, NOW(), NOW(), NULL),
(27, '45689', FALSE, NOW(), NOW(), NULL),
(27, '45717', FALSE, NOW(), NOW(), NULL),
(27, '1/4 ⭐', TRUE, NOW(), NOW(), NULL),
(27, '45718', FALSE, NOW(), NOW(), NULL),
(27, '45750', FALSE, NOW(), NOW(), NULL),
(28, '7', FALSE, NOW(), NOW(), NULL),
(28, '8', FALSE, NOW(), NOW(), NULL),
(28, '9 ⭐', TRUE, NOW(), NOW(), NULL),
(28, '10', FALSE, NOW(), NOW(), NULL),
(28, '11', FALSE, NOW(), NOW(), NULL),
(29, '12 cm²', FALSE, NOW(), NOW(), NULL),
(29, '18 cm²', FALSE, NOW(), NOW(), NULL),
(29, '24 cm²', FALSE, NOW(), NOW(), NULL),
(29, '36 cm² ⭐', TRUE, NOW(), NOW(), NULL),
(29, '48 cm²', FALSE, NOW(), NOW(), NULL),
(30, '9 cm', FALSE, NOW(), NOW(), NULL),
(30, '10 cm', FALSE, NOW(), NOW(), NULL),
(30, '11 cm', FALSE, NOW(), NOW(), NULL),
(30, '12 cm ⭐', TRUE, NOW(), NOW(), NULL),
(30, '13 cm', FALSE, NOW(), NOW(), NULL),
(31, '6', FALSE, NOW(), NOW(), NULL),
(31, '8 ⭐', TRUE, NOW(), NOW(), NULL),
(31, '9', FALSE, NOW(), NOW(), NULL),
(31, '12', FALSE, NOW(), NOW(), NULL),
(31, '16', FALSE, NOW(), NOW(), NULL),
(32, '90°', FALSE, NOW(), NOW(), NULL),
(32, '120°', FALSE, NOW(), NOW(), NULL),
(32, '180° ⭐', TRUE, NOW(), NOW(), NULL),
(32, '270°', FALSE, NOW(), NOW(), NULL),
(32, '360°', FALSE, NOW(), NOW(), NULL),
(33, '1', FALSE, NOW(), NOW(), NULL),
(33, '2 ⭐', TRUE, NOW(), NOW(), NULL),
(33, '3', FALSE, NOW(), NOW(), NULL),
(33, '4', FALSE, NOW(), NOW(), NULL),
(33, '10', FALSE, NOW(), NOW(), NULL),
(34, '6', FALSE, NOW(), NOW(), NULL),
(34, '7', FALSE, NOW(), NOW(), NULL),
(34, '8 ⭐', TRUE, NOW(), NOW(), NULL),
(34, '9', FALSE, NOW(), NOW(), NULL),
(34, '10', FALSE, NOW(), NOW(), NULL),
(35, '8 cm³', FALSE, NOW(), NOW(), NULL),
(35, '16 cm³', FALSE, NOW(), NOW(), NULL),
(35, '32 cm³', FALSE, NOW(), NOW(), NULL),
(35, '64 cm³ ⭐', TRUE, NOW(), NOW(), NULL),
(35, '128 cm³', FALSE, NOW(), NOW(), NULL),
(36, '2', FALSE, NOW(), NOW(), NULL),
(36, '3,14 ⭐', TRUE, NOW(), NOW(), NULL),
(36, '3,5', FALSE, NOW(), NOW(), NULL),
(36, '4', FALSE, NOW(), NOW(), NULL),
(36, '3,41', FALSE, NOW(), NOW(), NULL),
(37, '6', FALSE, NOW(), NOW(), NULL),
(37, '8', FALSE, NOW(), NOW(), NULL),
(37, '9', FALSE, NOW(), NOW(), NULL),
(37, '10 ⭐', TRUE, NOW(), NOW(), NULL),
(37, '12', FALSE, NOW(), NOW(), NULL),
(38, '7', FALSE, NOW(), NOW(), NULL),
(38, '8 ⭐', TRUE, NOW(), NOW(), NULL),
(38, '9', FALSE, NOW(), NOW(), NULL),
(38, '10', FALSE, NOW(), NOW(), NULL),
(38, '11', FALSE, NOW(), NOW(), NULL),
(39, 'Um lado maior', FALSE, NOW(), NOW(), NULL),
(39, 'Dois lados iguais', FALSE, NOW(), NOW(), NULL),
(39, 'Três lados iguais ⭐', TRUE, NOW(), NOW(), NULL),
(39, 'Nenhum lado igual', FALSE, NOW(), NOW(), NULL),
(39, 'Lados proporcionais', FALSE, NOW(), NOW(), NULL),
(40, 'O dobro do raio ⭐', TRUE, NOW(), NOW(), NULL),
(40, 'Igual ao raio', FALSE, NOW(), NOW(), NULL),
(40, 'A metade do raio', FALSE, NOW(), NOW(), NULL),
(40, 'O perímetro', FALSE, NOW(), NOW(), NULL),
(40, 'A área', FALSE, NOW(), NOW(), NULL),
(41, '0,25', FALSE, NOW(), NOW(), NULL),
(41, '0,5', FALSE, NOW(), NOW(), NULL),
(41, '75% ⭐', TRUE, NOW(), NOW(), NULL),
(41, '1', FALSE, NOW(), NOW(), NULL),
(41, '1,5', FALSE, NOW(), NOW(), NULL),
(42, '12', FALSE, NOW(), NOW(), NULL),
(42, '14', FALSE, NOW(), NOW(), NULL),
(42, '15', FALSE, NOW(), NOW(), NULL),
(42, '17 ⭐', TRUE, NOW(), NOW(), NULL),
(42, '18', FALSE, NOW(), NOW(), NULL),
(43, 'b × h', FALSE, NOW(), NOW(), NULL),
(43, '(b × h)/2 ⭐', TRUE, NOW(), NOW(), NULL),
(43, '2b × h', FALSE, NOW(), NOW(), NULL),
(43, '(2b)/h', FALSE, NOW(), NOW(), NULL),
(43, 'b + h', FALSE, NOW(), NOW(), NULL),
(44, '0,2 ⭐', TRUE, NOW(), NOW(), NULL),
(44, '2', FALSE, NOW(), NOW(), NULL),
(44, '1', FALSE, NOW(), NOW(), NULL),
(44, '10', FALSE, NOW(), NOW(), NULL),
(44, '0,5', FALSE, NOW(), NOW(), NULL),
(45, 'A variável dependente', FALSE, NOW(), NOW(), NULL),
(45, 'A variável independente ⭐', TRUE, NOW(), NOW(), NULL),
(45, 'O valor máximo', FALSE, NOW(), NOW(), NULL),
(45, 'O ponto médio', FALSE, NOW(), NOW(), NULL),
(45, 'A área', FALSE, NOW(), NOW(), NULL),
(46, '10', FALSE, NOW(), NOW(), NULL),
(46, '15', FALSE, NOW(), NOW(), NULL),
(46, '20 ⭐', TRUE, NOW(), NOW(), NULL),
(46, '25', FALSE, NOW(), NOW(), NULL),
(46, '30', FALSE, NOW(), NOW(), NULL),
(47, '45717', FALSE, NOW(), NOW(), NULL),
(47, '1/2 ⭐', TRUE, NOW(), NOW(), NULL),
(47, '45748', FALSE, NOW(), NOW(), NULL),
(47, '45718', FALSE, NOW(), NOW(), NULL),
(47, '45750', FALSE, NOW(), NOW(), NULL),
(48, '-9', FALSE, NOW(), NOW(), NULL),
(48, '6', FALSE, NOW(), NOW(), NULL),
(48, '9 ⭐', TRUE, NOW(), NOW(), NULL),
(48, '0', FALSE, NOW(), NOW(), NULL),
(48, '-6', FALSE, NOW(), NOW(), NULL),
(49, '11', FALSE, NOW(), NOW(), NULL),
(49, '16', FALSE, NOW(), NOW(), NULL),
(49, '21 ⭐', TRUE, NOW(), NOW(), NULL),
(49, '24', FALSE, NOW(), NOW(), NULL),
(49, '25', FALSE, NOW(), NOW(), NULL),
(50, 'Apenas positivos', FALSE, NOW(), NOW(), NULL),
(50, 'Positivos e negativos ⭐', TRUE, NOW(), NOW(), NULL),
(50, 'Apenas negativos', FALSE, NOW(), NOW(), NULL),
(50, 'Apenas decimais', FALSE, NOW(), NOW(), NULL),
(50, 'Apenas pares', FALSE, NOW(), NOW(), NULL),
(51, 'Tratar de temas históricos', FALSE, NOW(), NOW(), NULL),
(51, 'Apresentar linguagem técnica', FALSE, NOW(), NOW(), NULL),
(51, 'Narrar fatos do cotidiano com tom reflexivo ⭐', TRUE, NOW(), NOW(), NULL),
(51, 'Ser um texto científico', FALSE, NOW(), NOW(), NULL),
(51, 'Seguir estrutura fixa', FALSE, NOW(), NOW(), NULL),
(52, 'Indica uma ação', FALSE, NOW(), NOW(), NULL),
(52, 'Determina o verbo', FALSE, NOW(), NOW(), NULL),
(52, 'Indica quem pratica ou sofre a ação ⭐', TRUE, NOW(), NOW(), NULL),
(52, 'Liga orações', FALSE, NOW(), NOW(), NULL),
(52, 'Encerra o período', FALSE, NOW(), NOW(), NULL),
(53, 'Modifica substantivos', FALSE, NOW(), NOW(), NULL),
(53, 'Modifica verbos, adjetivos ou outros advérbios ⭐', TRUE, NOW(), NOW(), NULL),
(53, 'Indica posse', FALSE, NOW(), NOW(), NULL),
(53, 'Substitui o sujeito', FALSE, NOW(), NOW(), NULL),
(53, 'Liga orações', FALSE, NOW(), NOW(), NULL),
(54, 'O sentido das palavras é literal', FALSE, NOW(), NOW(), NULL),
(54, 'Há uso figurado da linguagem ⭐', TRUE, NOW(), NOW(), NULL),
(54, 'O texto é técnico', FALSE, NOW(), NOW(), NULL),
(54, 'Há definições científicas', FALSE, NOW(), NOW(), NULL),
(54, 'O texto é jurídico', FALSE, NOW(), NOW(), NULL),
(55, 'Semana de Arte Moderna de 1922 ⭐', TRUE, NOW(), NOW(), NULL),
(55, 'Romantismo', FALSE, NOW(), NOW(), NULL),
(55, 'Naturalismo', FALSE, NOW(), NOW(), NULL),
(55, 'Simbolismo', FALSE, NOW(), NOW(), NULL),
(55, 'Realismo', FALSE, NOW(), NOW(), NULL),
(56, 'Cidadões', FALSE, NOW(), NOW(), NULL),
(56, 'Cidadãos ⭐', TRUE, NOW(), NOW(), NULL),
(56, 'Cidadães', FALSE, NOW(), NOW(), NULL),
(56, 'Cidadãs', FALSE, NOW(), NOW(), NULL),
(56, 'Cidadan', FALSE, NOW(), NOW(), NULL),
(57, 'Estudei', FALSE, NOW(), NOW(), NULL),
(57, 'Estudava', FALSE, NOW(), NOW(), NULL),
(57, 'Estudarei ⭐', TRUE, NOW(), NOW(), NULL),
(57, 'Estudara', FALSE, NOW(), NOW(), NULL),
(57, 'Estudaria', FALSE, NOW(), NOW(), NULL),
(58, 'Sujeito', FALSE, NOW(), NOW(), NULL),
(58, 'Objeto direto ⭐', TRUE, NOW(), NOW(), NULL),
(58, 'Objeto indireto', FALSE, NOW(), NOW(), NULL),
(58, 'Predicativo', FALSE, NOW(), NOW(), NULL),
(58, 'Vocativo', FALSE, NOW(), NOW(), NULL),
(59, 'Informar', FALSE, NOW(), NOW(), NULL),
(59, 'Convencer o leitor a uma ação ⭐', TRUE, NOW(), NOW(), NULL),
(59, 'Narrar uma história', FALSE, NOW(), NOW(), NULL),
(59, 'Descrever paisagens', FALSE, NOW(), NOW(), NULL),
(59, 'Definir conceitos', FALSE, NOW(), NOW(), NULL),
(60, 'Crônica', FALSE, NOW(), NOW(), NULL),
(60, 'Poema ⭐', TRUE, NOW(), NOW(), NULL),
(60, 'Notícia', FALSE, NOW(), NOW(), NULL),
(60, 'Editorial', FALSE, NOW(), NOW(), NULL),
(60, 'Ensaio', FALSE, NOW(), NOW(), NULL),
(61, 'Gil Vicente', FALSE, NOW(), NOW(), NULL),
(61, 'Camilo Castelo Branco', FALSE, NOW(), NOW(), NULL),
(61, 'Luís de Camões ⭐', TRUE, NOW(), NOW(), NULL),
(61, 'Eça de Queirós', FALSE, NOW(), NOW(), NULL),
(61, 'Fernando Pessoa', FALSE, NOW(), NOW(), NULL),
(62, 'José de Alencar', FALSE, NOW(), NOW(), NULL),
(62, 'Machado de Assis ⭐', TRUE, NOW(), NOW(), NULL),
(62, 'Lima Barreto', FALSE, NOW(), NOW(), NULL),
(62, 'Graciliano Ramos', FALSE, NOW(), NOW(), NULL),
(62, 'Jorge Amado', FALSE, NOW(), NOW(), NULL),
(63, 'Metonímia', FALSE, NOW(), NOW(), NULL),
(63, 'Metáfora ⭐', TRUE, NOW(), NOW(), NULL),
(63, 'Antítese', FALSE, NOW(), NOW(), NULL),
(63, 'Hipérbole', FALSE, NOW(), NOW(), NULL),
(63, 'Ironia', FALSE, NOW(), NOW(), NULL),
(64, 'Verbo', FALSE, NOW(), NOW(), NULL),
(64, 'Substantivo', FALSE, NOW(), NOW(), NULL),
(64, 'Advérbio ⭐', TRUE, NOW(), NOW(), NULL),
(64, 'Adjetivo', FALSE, NOW(), NOW(), NULL),
(64, 'Conjunção', FALSE, NOW(), NOW(), NULL),
(65, 'Falas narradas indiretamente', FALSE, NOW(), NOW(), NULL),
(65, 'Uso de travessões e falas literais ⭐', TRUE, NOW(), NOW(), NULL),
(65, 'Verbos de elocução ocultos', FALSE, NOW(), NOW(), NULL),
(65, 'Falta de pontuação', FALSE, NOW(), NOW(), NULL),
(65, 'Frases curtas', FALSE, NOW(), NOW(), NULL),
(66, 'Erros de linguagem', FALSE, NOW(), NOW(), NULL),
(66, 'Diferenças regionais e sociais ⭐', TRUE, NOW(), NOW(), NULL),
(66, 'Falta de norma culta', FALSE, NOW(), NOW(), NULL),
(66, 'Desrespeito à gramática', FALSE, NOW(), NOW(), NULL),
(66, 'Falta de vocabulário', FALSE, NOW(), NOW(), NULL),
(67, 'Há repetição de ideias', FALSE, NOW(), NOW(), NULL),
(67, 'Um texto dialoga com outro ⭐', TRUE, NOW(), NOW(), NULL),
(67, 'O texto é objetivo', FALSE, NOW(), NOW(), NULL),
(67, 'O autor repete palavras', FALSE, NOW(), NOW(), NULL),
(67, 'A linguagem é técnica', FALSE, NOW(), NOW(), NULL),
(68, 'Subjetividade', FALSE, NOW(), NOW(), NULL),
(68, 'Fatos reais e recentes ⭐', TRUE, NOW(), NOW(), NULL),
(68, 'Uso de metáforas', FALSE, NOW(), NOW(), NULL),
(68, 'Humor', FALSE, NOW(), NOW(), NULL),
(68, 'Linguagem poética', FALSE, NOW(), NOW(), NULL),
(69, 'Substantivo', FALSE, NOW(), NOW(), NULL),
(69, 'Adjetivo ⭐', TRUE, NOW(), NOW(), NULL),
(69, 'Advérbio', FALSE, NOW(), NOW(), NULL),
(69, 'Verbo', FALSE, NOW(), NOW(), NULL),
(69, 'Pronome', FALSE, NOW(), NOW(), NULL),
(70, 'Iam', FALSE, NOW(), NOW(), NULL),
(70, 'Foram ⭐', TRUE, NOW(), NOW(), NULL),
(70, 'Irem', FALSE, NOW(), NOW(), NULL),
(70, 'Ido', FALSE, NOW(), NOW(), NULL),
(70, 'Irão', FALSE, NOW(), NOW(), NULL),
(71, 'Obras de teatro', FALSE, NOW(), NOW(), NULL),
(71, 'Poemas com heterônimos ⭐', TRUE, NOW(), NOW(), NULL),
(71, 'Textos jornalísticos', FALSE, NOW(), NOW(), NULL),
(71, 'Crônicas políticas', FALSE, NOW(), NOW(), NULL),
(71, 'Ensaios técnicos', FALSE, NOW(), NOW(), NULL),
(72, 'No emissor ⭐', TRUE, NOW(), NOW(), NULL),
(72, 'No receptor', FALSE, NOW(), NOW(), NULL),
(72, 'Na mensagem', FALSE, NOW(), NOW(), NULL),
(72, 'No canal', FALSE, NOW(), NOW(), NULL),
(72, 'No código', FALSE, NOW(), NOW(), NULL),
(73, 'Função poética', FALSE, NOW(), NOW(), NULL),
(73, 'Função conativa ⭐', TRUE, NOW(), NOW(), NULL),
(73, 'Função referencial', FALSE, NOW(), NOW(), NULL),
(73, 'Função fática', FALSE, NOW(), NOW(), NULL),
(73, 'Função metalinguística', FALSE, NOW(), NOW(), NULL),
(74, 'Mãos ⭐', TRUE, NOW(), NOW(), NULL),
(74, 'Mões', FALSE, NOW(), NOW(), NULL),
(74, 'Mães', FALSE, NOW(), NOW(), NULL),
(74, 'Mans', FALSE, NOW(), NOW(), NULL),
(74, 'Manos', FALSE, NOW(), NOW(), NULL),
(75, 'Sou ⭐', TRUE, NOW(), NOW(), NULL),
(75, 'És', FALSE, NOW(), NOW(), NULL),
(75, 'É', FALSE, NOW(), NOW(), NULL),
(75, 'Somos', FALSE, NOW(), NOW(), NULL),
(75, 'São', FALSE, NOW(), NOW(), NULL),
(76, 'Ordem e progresso', FALSE, NOW(), NOW(), NULL),
(76, 'Liberdade, Igualdade e Fraternidade ⭐', TRUE, NOW(), NOW(), NULL),
(76, 'Fé e tradição', FALSE, NOW(), NOW(), NULL),
(76, 'Pão e terra', FALSE, NOW(), NOW(), NULL),
(76, 'Paz e trabalho', FALSE, NOW(), NOW(), NULL),
(77, 'Absolutismo monárquico ⭐', TRUE, NOW(), NOW(), NULL),
(77, 'Liberalismo econômico', FALSE, NOW(), NOW(), NULL),
(77, 'Racionalismo', FALSE, NOW(), NOW(), NULL),
(77, 'Socialismo', FALSE, NOW(), NOW(), NULL),
(77, 'Positivismo', FALSE, NOW(), NOW(), NULL),
(78, 'Trabalho assalariado', FALSE, NOW(), NOW(), NULL),
(78, 'Produção agrícola de subsistência ⭐', TRUE, NOW(), NOW(), NULL),
(78, 'Comércio internacional', FALSE, NOW(), NOW(), NULL),
(78, 'Democracia representativa', FALSE, NOW(), NOW(), NULL),
(78, 'Centralização política', FALSE, NOW(), NOW(), NULL),
(79, 'Produção de açúcar nas fazendas coloniais ⭐', TRUE, NOW(), NOW(), NULL),
(79, 'Formação de universidades', FALSE, NOW(), NOW(), NULL),
(79, 'Revolta dos bandeirantes', FALSE, NOW(), NOW(), NULL),
(79, 'Criação de cooperativas', FALSE, NOW(), NOW(), NULL),
(79, 'Independência do país', FALSE, NOW(), NOW(), NULL),
(80, 'Disputa ideológica entre EUA e URSS ⭐', TRUE, NOW(), NOW(), NULL),
(80, 'Conflitos diretos', FALSE, NOW(), NOW(), NULL),
(80, 'Guerras religiosas', FALSE, NOW(), NOW(), NULL),
(80, 'União política entre países', FALSE, NOW(), NOW(), NULL),
(80, 'Expansão colonial', FALSE, NOW(), NOW(), NULL),
(81, 'Acúmulo de metais preciosos ⭐', TRUE, NOW(), NOW(), NULL),
(81, 'Livre comércio', FALSE, NOW(), NOW(), NULL),
(81, 'Separação de poderes', FALSE, NOW(), NOW(), NULL),
(81, 'Economia planificada', FALSE, NOW(), NOW(), NULL),
(81, 'Agricultura de subsistência', FALSE, NOW(), NOW(), NULL),
(82, 'Expansão rural', FALSE, NOW(), NOW(), NULL),
(82, 'Problemas habitacionais e de transporte ⭐', TRUE, NOW(), NOW(), NULL),
(82, 'Redução das cidades', FALSE, NOW(), NOW(), NULL),
(82, 'Diminuição da desigualdade', FALSE, NOW(), NOW(), NULL),
(82, 'Êxodo urbano', FALSE, NOW(), NOW(), NULL),
(83, 'Manter a paz mundial ⭐', TRUE, NOW(), NOW(), NULL),
(83, 'Administrar colônias', FALSE, NOW(), NOW(), NULL),
(83, 'Controlar o comércio', FALSE, NOW(), NOW(), NULL),
(83, 'Promover guerras', FALSE, NOW(), NOW(), NULL),
(83, 'Criar fronteiras', FALSE, NOW(), NOW(), NULL),
(84, 'Inglaterra ⭐', TRUE, NOW(), NOW(), NULL),
(84, 'França', FALSE, NOW(), NOW(), NULL),
(84, 'Alemanha', FALSE, NOW(), NOW(), NULL),
(84, 'Itália', FALSE, NOW(), NOW(), NULL),
(84, 'Rússia', FALSE, NOW(), NOW(), NULL),
(85, 'Segregação racial na África do Sul ⭐', TRUE, NOW(), NOW(), NULL),
(85, 'Igualdade política', FALSE, NOW(), NOW(), NULL),
(85, 'Governo democrático', FALSE, NOW(), NOW(), NULL),
(85, 'Monarquia parlamentar', FALSE, NOW(), NOW(), NULL),
(85, 'Socialismo democrático', FALSE, NOW(), NOW(), NULL),
(86, 'Ampliou direitos sociais ⭐', TRUE, NOW(), NOW(), NULL),
(86, 'Reduziu a democracia', FALSE, NOW(), NOW(), NULL),
(86, 'Centralizou o poder', FALSE, NOW(), NOW(), NULL),
(86, 'Instituiu o voto indireto', FALSE, NOW(), NOW(), NULL),
(86, 'Fortaleceu o militarismo', FALSE, NOW(), NOW(), NULL),
(87, 'Portugal e Espanha ⭐', TRUE, NOW(), NOW(), NULL),
(87, 'França e Inglaterra', FALSE, NOW(), NOW(), NULL),
(87, 'Holanda e Espanha', FALSE, NOW(), NOW(), NULL),
(87, 'Itália e Portugal', FALSE, NOW(), NOW(), NULL),
(87, 'França e Portugal', FALSE, NOW(), NOW(), NULL),
(88, 'Explorar o trabalhador ⭐', TRUE, NOW(), NOW(), NULL),
(88, 'Gerar igualdade', FALSE, NOW(), NOW(), NULL),
(88, 'Eliminar a burguesia', FALSE, NOW(), NOW(), NULL),
(88, 'Criar o socialismo', FALSE, NOW(), NOW(), NULL),
(88, 'Defender o comunismo', FALSE, NOW(), NOW(), NULL),
(89, 'Escravos muçulmanos ⭐', TRUE, NOW(), NOW(), NULL),
(89, 'Comerciantes brancos', FALSE, NOW(), NOW(), NULL),
(89, 'Fazendeiros', FALSE, NOW(), NOW(), NULL),
(89, 'Soldados portugueses', FALSE, NOW(), NOW(), NULL),
(89, 'Índios aldeados', FALSE, NOW(), NOW(), NULL),
(90, 'O antropocentrismo ⭐', TRUE, NOW(), NOW(), NULL),
(90, 'O teocentrismo', FALSE, NOW(), NOW(), NULL),
(90, 'O feudalismo', FALSE, NOW(), NOW(), NULL),
(90, 'O mercantilismo', FALSE, NOW(), NOW(), NULL),
(90, 'A fé religiosa', FALSE, NOW(), NOW(), NULL),
(91, 'Brasil, Argentina e Uruguai ⭐', TRUE, NOW(), NOW(), NULL),
(91, 'Chile e Bolívia', FALSE, NOW(), NOW(), NULL),
(91, 'Colômbia e Venezuela', FALSE, NOW(), NOW(), NULL),
(91, 'México e Peru', FALSE, NOW(), NOW(), NULL),
(91, 'Equador e Bolívia', FALSE, NOW(), NOW(), NULL),
(92, 'Direitos e deveres dos indivíduos ⭐', TRUE, NOW(), NOW(), NULL),
(92, 'Herança familiar', FALSE, NOW(), NOW(), NULL),
(92, 'Propriedade privada', FALSE, NOW(), NOW(), NULL),
(92, 'Nacionalismo', FALSE, NOW(), NOW(), NULL),
(92, 'Cultura popular', FALSE, NOW(), NOW(), NULL),
(93, 'Redução do papel do Estado na economia ⭐', TRUE, NOW(), NOW(), NULL),
(93, 'Estatização', FALSE, NOW(), NOW(), NULL),
(93, 'Protecionismo', FALSE, NOW(), NOW(), NULL),
(93, 'Planejamento centralizado', FALSE, NOW(), NOW(), NULL),
(93, 'Autossuficiência nacional', FALSE, NOW(), NOW(), NULL),
(94, 'Eleições diretas para presidente ⭐', TRUE, NOW(), NOW(), NULL),
(94, 'Fim do voto obrigatório', FALSE, NOW(), NOW(), NULL),
(94, 'Retorno à monarquia', FALSE, NOW(), NOW(), NULL),
(94, 'Adoção do parlamentarismo', FALSE, NOW(), NOW(), NULL),
(94, 'Fim da censura', FALSE, NOW(), NOW(), NULL),
(95, 'Interação entre sociedade e natureza ⭐', TRUE, NOW(), NOW(), NULL),
(95, 'Apenas o espaço natural', FALSE, NOW(), NOW(), NULL),
(95, 'Clima e solo', FALSE, NOW(), NOW(), NULL),
(95, 'Uso de tecnologias', FALSE, NOW(), NOW(), NULL),
(95, 'Ação humana isolada', FALSE, NOW(), NOW(), NULL),
(96, 'O lucro obtido pela exploração do trabalho ⭐', TRUE, NOW(), NOW(), NULL),
(96, 'A divisão igual de renda', FALSE, NOW(), NOW(), NULL),
(96, 'O papel do Estado', FALSE, NOW(), NOW(), NULL),
(96, 'O equilíbrio de mercado', FALSE, NOW(), NOW(), NULL),
(96, 'O preço do trabalho', FALSE, NOW(), NOW(), NULL),
(97, 'Nacionalismos e alianças militares ⭐', TRUE, NOW(), NOW(), NULL),
(97, 'Revoltas camponesas', FALSE, NOW(), NOW(), NULL),
(97, 'Expansão marítima', FALSE, NOW(), NOW(), NULL),
(97, 'Fome na Europa', FALSE, NOW(), NOW(), NULL),
(97, 'Avanço do socialismo', FALSE, NOW(), NOW(), NULL),
(98, 'A razão e a ciência ⭐', TRUE, NOW(), NOW(), NULL),
(98, 'A fé e a tradição', FALSE, NOW(), NOW(), NULL),
(98, 'O poder da Igreja', FALSE, NOW(), NOW(), NULL),
(98, 'O absolutismo', FALSE, NOW(), NOW(), NULL),
(98, 'O misticismo', FALSE, NOW(), NOW(), NULL),
(99, 'Propriedade privada e livre mercado ⭐', TRUE, NOW(), NOW(), NULL),
(99, 'Coletivização da economia', FALSE, NOW(), NOW(), NULL),
(99, 'Igualdade de renda', FALSE, NOW(), NOW(), NULL),
(99, 'Planejamento estatal', FALSE, NOW(), NOW(), NULL),
(99, 'Controle social', FALSE, NOW(), NOW(), NULL),
(100, 'Dom Pedro I ⭐', TRUE, NOW(), NOW(), NULL),
(100, 'Dom João VI', FALSE, NOW(), NOW(), NULL),
(100, 'José Bonifácio', FALSE, NOW(), NOW(), NULL),
(100, 'Tiradentes', FALSE, NOW(), NOW(), NULL),
(100, 'Getúlio Vargas', FALSE, NOW(), NOW(), NULL);